# Generated by Django 5.2.4 on 2025-07-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_productspecs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSpecs',
            new_name='ProductSpec',
        ),
    ]
